CREATE TABLE IF NOT EXISTS users (
	user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(100) NOT NULL,
	email varchar(100) NOT NULL,
	birthday date NOT NULL,
	name varchar(100) NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id int,
    name varchar(100) NOT NULL,
    CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
   );
  
  CREATE TABLE IF NOT EXISTS genre (
    genre_id int,
    name varchar(100) NOT NULL,
    CONSTRAINT genre_pk PRIMARY KEY (genre_id)
   );

CREATE TABLE IF NOT EXISTS film (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    description varchar(200) NOT NULL,
    release_date date NOT NULL,
    duration int CHECK(duration >0) NOT NULL,
    mpa_id int REFERENCES mpa(mpa_id)
   );
   
CREATE TABLE IF NOT EXISTS film_genre (
    film_id int REFERENCES film(film_id),
    genre_id int REFERENCES genre(genre_id)
   );
 

CREATE TABLE IF NOT EXISTS user_friend (
    user_id int REFERENCES users(user_id),
    friend_id int REFERENCES users(user_id)
   );

CREATE TABLE IF NOT EXISTS film_like (
    film_id int REFERENCES film(film_id),
    user_id int REFERENCES users(user_id)
   );



